version: "3"
services:
  elasticsearch:
    image: elasticsearch
    networks:
      - docker_elk
  kibana:
    image: kibana
    links:
      - elasticsearch
    networks:
      - docker_elk
  nginx:
    image: nginx
    ports:
      - "1337:80"
    links:
      - kibana
      - node
    networks:
      - docker_elk
    volumes:
      - ./fp-nginx/passwd:/etc/nginx/passwd
      - ./fp-nginx/default.conf:/etc/nginx/conf.d/default.conf
  node:
   image: fp-demo
   links:
     - elasticsearch
     - kibana
   networks:
     - docker_elk
   depends_on:
     - elasticsearch
     - kibana
networks:
  docker_elk:
    driver: bridge
