version: "3"
services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./data:/usr/share/elasticsearch/data elasticsearch
    networks:
      - docker_elk
  kibana:
    image: kibana
    links:
      - elasticsearch
    networks:
      - docker_elk
  node:
    image:
    links:
      - elasticsearch
    networks:
      - docker_elk
  nginx:
    image:
    ports: "1337:1337"
    links:
      - kibana
      - node
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge
