version: "3"
services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./data:/usr/share/elasticsearch/data elasticsearch
    networks:
      - docker_elk
  kibana:
    image: kibana
    links:
      - elasticsearch
    networks:
      - docker_elk
  node:
    image: fp-demo
    ports:
      - "1337:1337"
    links:
      - elasticsearch
      - kibana
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
      - kibana
  nginx:
    image: nginx
    ports:
      - "8080:80"
    links:
      - kibana
      - node
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge
